__default__:
  name: "rule={rule},{wildcards}" # -J
  partition: compute # -p
  time: "3-00:00:00"  # -t
  cpusPerTask: "{threads}" # -c
  memPerCpu: 20G # --mem-per-cpu
  nodes: 1
  output: "output/logs_slurm/{rule}.{wildcards}.{jobid}.out"
  error: "output/logs_slurm/{rule}.{wildcards}.{jobid}.err"

## Multi-threaded / High-memory Rules
align:
  memPerCpu: 20G

sort:
  memPerCpu: 20G

mergedSort:
  memPerCpu: 20G

hic:
  memPerCpu: 26G
  time: "7-00:00:00"

hic30:
  memPerCpu: 26G
  time: "7-00:00:00"
  
norm:
  memPerCpu: 26G
  time: "7-00:00:00"
  
norm30:
  memPerCpu: 26G
  time: "7-00:00:00"
