## Path to sample sheet
samplesheet: 'samplesheet.txt'

## List columns to group (i.e. any columns left out will become part of the same group)
groupBy: ['Project', 'Cell_Type', 'Genotype']

## Genome-specific reference parameters
fasta: '/home/watamine/references/hg38/hg38.fa' 
chromSizes: '/home/watamine/references/hg38_Arima/hg38_Arima.chrom.sizes'

## Restriction site information
site: "Arima" # or 'none'
site_file: '/home/watamine/references/hg38_Arima/hg38_Arima.txt' # Make sure chromosomes match bwa index chromosomes (i.e. both start with "chr")
ligation: "GATCGATC"

## Set splitsize
splitsize: 200000000 ## 200000000 good default (50M reads/file) (i.e. 4000000 = 1M reads/file) 

## Java memory for buildHiC (hic/norm rules)
javaMem: "250880"

## Additional options
mapq0_reads_included: 0
